import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import IOSCursor from "@/components/Cursor";
import { bitcount, monocraft } from "./font";
import FaultyTerminalWrapper from "@/components/FaultyWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bitcount.variable} ${monocraft.variable}`}>
      <head>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com"> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Bitcount+Prop+Double+Ink:wght@100..900&family=Bitcount+Prop+Single+Ink:wght@100..900&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <IOSCursor />
          {/* FaultyTerminal as sticky background */}
          <div className="fixed inset-0 -z-10 backdrop-blur-3xl">
            <FaultyTerminalWrapper
            // backgroundColor="#855454ff"
            />
          </div>
          <div className="">
            {/* <Sidebar /> */}
            {children}
            {/* <TOC /> */}
          </div>
          {/* <DockMenu /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
