import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import IOSCursor from "@/components/Cursor";
import FaultyTerminal from "@/components/FaultyTerminal"; // <-- Add this import
import { bitcount, monocraft } from "./font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bitcount.variable} ${monocraft.variable}`}>
      <head>
        {/* <link rel="preconnect" href="https://fonts.googleapis.com"> */}
        {/* <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> */}
        <link href="https://fonts.googleapis.com/css2?family=Bitcount+Prop+Double+Ink:wght@100..900&family=Bitcount+Prop+Single+Ink:wght@100..900&display=swap" rel="stylesheet"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <IOSCursor />
          {/* FaultyTerminal as sticky background */}
          <div className="fixed inset-0 -z-10">
            <FaultyTerminal
              scale={1.5}
              gridMul={[2, 1]}
              digitSize={1}
              timeScale={0.5}
              pause={false}
              scanlineIntensity={0.5}
              glitchAmount={0.5}
              flickerAmount={0.5}
              noiseAmp={0.5}
              chromaticAberration={0}
              dither={0}
              curvature={0}
              tint="#d97532ff"
              mouseReact={false}
              mouseStrength={0.1}
              pageLoadAnimation={true}
              brightness={0.5}
              // backgroundColor="#855454ff"
            />
          </div>
          <div className="">
            {/* <Sidebar /> */}
            {children}
            {/* <TOC /> */}
          </div>
          {/* <DockMenu /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
